spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    bot-username: ${TELEGRAM_BOT_USERNAME}
  ai:
    api-key: ${GROQ_API_KEY}
    base-url: ${AI_BASE_URL}
